"""update setting key unique

Revision ID: 248521830967
Revises: 7cce275f827a
Create Date: 2026-07-14 20:13:28.806428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '248521830967'
down_revision: Union[str, Sequence[str], None] = '7cce275f827a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_setting_group_key'), 'setting', type_='unique')
    op.create_unique_constraint(None, 'setting', ['key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'setting', type_='unique')
    op.create_unique_constraint(op.f('uq_setting_group_key'), 'setting', ['group_id', 'key'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
