"""delete product brand

Revision ID: 42f9e206b2a3
Revises: f4f4f7af250b
Create Date: 2026-06-26 10:39:51.817005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42f9e206b2a3'
down_revision: Union[str, Sequence[str], None] = 'f4f4f7af250b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'brand')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('brand', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
